[package]
name = "email-blaster"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.2.2"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = { version = "1.0.80", features = [] }
lettre = "0.10.4"
walkdir = "2.4.0"
mime = "0.3.17"
mime_guess = "2.0.4"
base64 = "0.21.4"